rootContext: {}
stream: false

steps:

  # ── LIFTS ──────────────────────────────────────────────────────────────────
  - type: request
    name: "Fetch DSS Lifts"
    request:
      url: "https://www.dolomitisuperski.com/jsonexport/export/liftbasis"
      method: GET
      auth:
        type: basic
        username: "${DSS_USERNAME}"
        password: "${DSS_PASSWORD}"
    resultTransformer: "."
    mergeOn: .dssLifts = $res