options:
  streamRootArray: true

rootContext: []

auth:
  type: custom
  loginRequest:
    url: "https://auth-api.eu-venueops.com/token"
    method: POST
    headers:
      Content-Type: "application/json"
    body:
      clientId: "${MOMENTUS_CLIENT_ID}"
      clientSecret: "${MOMENTUS_CLIENT_SECRET}"
  extractFrom: body
  extractSelector: '"Bearer " + .accessToken'
  injectInto: header
  injectKey: Authorization
  maxAgeSeconds: 3000

steps:
  - type: request
    name: "Fetch Events Base List"
    request:
      method: POST
      url: "https://api.eu-venueops.com/v1/events/query-by-date-range"
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
      body:
        start: '{{ now | dateModify "-1d" | date "2006-01-02" }}'
        end: '{{ now | dateModify "+30d" | date "2006-01-02" }}'
        includeBookedSpaces: true
        venueIds:
          - "venue-1-A"
        roomIds:
          - "room-1-A"
          - "room-55-A"
          - "room-58-A"
          - "room-2-A"
          - "room-4-A"
          - "room-5-A"
          - "room-48-A"
          - "room-6-A"

    resultTransformer: "map(select(.bookedSpaces | type == \"array\" and any(.[]; .usageType == \"event\")))"

