rootContext: {}
stream: false

# Collector: Panomax Webcams
# Source:  https://api.panomax.com/1.0/instances/lists/public
# Target:  ODH WebcamInfo endpoint

steps:

  - type: request
    name: "Fetch Panomax Webcams"
    request:
      url: "https://api.panomax.com/1.0/instances/lists/public"
      method: GET
    resultTransformer: "."
