rootContext: {}
stream: false

steps:
  # ── Snowparks ─────────────────────────────────────────────────────────────────
  - type: request
    name: "Fetch DSS Snowparks"
    request:
      url: "https://www.dolomitisuperski.com/jsonexport/export/snowparks?username=${DSS_USERNAME}&password=${DSS_PASSWORD}"
      method: GET
    resultTransformer: "."
    mergeOn: .dssSnowparks = $res
