rootContext: {}
stream: false

steps:
  # ── Webcams ─────────────────────────────────────────────────────────────────
  - type: request
    name: "Fetch DSS Webcams"
    request:
      url: "https://www.dolomitisuperski.com/jsonexport/export/webcams"
      method: GET
      auth:
        type: basic
        username: "${DSS_USERNAME}"
        password: "${DSS_PASSWORD}"
    resultTransformer: "."
    mergeOn: .dssWebcams = $res
