# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

###
@host=https://mobility.api.dev.testingmachine.eu
@origin={{$dotenv BDP_ORIGIN}}

###
GET {{host}}/flat,event/{{origin}}