replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-parking-offstreet-sfhera
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: sometaghere

imagePullSecrets:
  - name: container-registry-r

nameOverride: "tr-parking-offstreet-sfhera"
fullnameOverride: "tr-parking-offstreet-sfhera"

env:
  # Alperia Config
  app_callerId: NOI-Techpark
  app_dataOrigin: route220
  app_period: 600
  
  # ODH Core Writer Connection
  BASE_URI: http://bdp-core.core.svc.cluster.local:8080/json
  scope: openid
  
  provenance_name: dc-emobility-echarging-local
  provenance_version: 0.0.0
  
  # Logging level and style (text or json)
  LOG_LEVEL: info
  LOG_STYLE: json
  
  MQ_LISTEN_KEY: echarging.route220
  MQ_LISTEN_QUEUE: echarging.route220
  MQ_LISTEN_ACKTIMEOUT: 300000
  
envSecretRef:
  - name: MQ_LISTEN_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_CONNECTIONSTRING
    secret: mongodb-collector-svcbind
    key: uri

  - name: authorizationUri
    secret: oauth-collector
    key: authorizationUri
  - name: tokenUri
    secret: oauth-collector
    key: tokenUri
  - name: clientId
    secret: oauth-collector
    key: clientId
  - name: clientName
    secret: oauth-collector
    key: clientId
  - name: clientSecret
    secret: oauth-collector
    key: clientSecret