# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  test:
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile
      target: test
