env:
  # ODH Core Writer Connection
  BDP_BASE_URL: https://share.opendatahub.testingmachine.eu
  BDP_PROVENANCE_NAME: 
  BDP_PROVENANCE_VERSION: 
  BDP_ORIGIN: AXIANS
  
  LOG_LEVEL: INFO

  MQ_EXCHANGE: routed
  MQ_QUEUE: parking-onstreet.bz-axians
  MQ_KEY: parking-onstreet.bz-axians
  MQ_CONSUMER: tr-parking-onstreet-bz
  
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_URI
    secret: mongodb-collector-svcbind
    key: uri

  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret