# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-meteorology-bz-forecast
  pullPolicy: IfNotPresent
  tag: sometaghere

imagePullSecrets:
  - name: container-registry-r

env:
  # ODH Core Writer Connection
  LOG_LEVEL: "DEBUG"
  MQ_QUEUE: s3-poller.meteorology-bz-forecast
  MQ_EXCHANGE: routed  
  MQ_KEY: s3-poller.meteorology-bz-forecast
  MQ_CLIENT: tr-meteorology-bz-forecast

  BDP_BASE_URL: https://mobility.share.opendatahub.com
  BDP_PROVENANCE_VERSION: 
  BDP_PROVENANCE_NAME: 
  BDP_ORIGIN: province-bolzano

  RAW_DATA_BRIDGE_ENDPOINT: http://raw-data-bridge.core.svc.cluster.local:2000

envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret
