# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  app:
    image: maven:3-openjdk-17-slim
    env_file:
      - .env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000"
    command: >
      mvn
      -Duser.home=/var/maven
      spring-boot:run
    volumes:
      - ~/.m2/:/var/maven/.m2
      - ./:/code
    working_dir: /code
    ports:
      - 9000:9000
    tty: true
    extra_hosts:
      - "rabbitmq.core.svc.cluster.local:172.17.0.1"
      - "mongodb-headless.core.svc.cluster.local:172.17.0.1"
      - "bdp-core.core.svc.cluster.local:172.17.0.1"
