image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-matomo
  pullPolicy: IfNotPresent

env:
  # ODH Core Writer Connection
  BDP_BASE_URL: http://bdp-core.core.svc.cluster.local
  BDP_PROVENANCE_NAME: 
  BDP_PROVENANCE_VERSION: 
  BDP_ORIGIN: noibzit
  
  LOG_LEVEL: INFO

  MQ_QUEUE: matomo.noi-transparency
  MQ_EXCHANGE: routed
  MQ_KEY: matomo.noi-transparency
  MQ_CLIENT: tr-matomo.noi-transparency

  PERIOD: 72000
  REPORT_ID: noi.bz.it/transparency
  REPORT_NAME: noi.bz.it/transparency

  RAW_DATA_BRIDGE_ENDPOINT: http://raw-data-bridge.core.svc.cluster.local:2000

  SERVICE_NAME: tr-matomo-noi-transparency
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317
  
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_URI
    secret: mongodb-collector-svcbind
    key: uri

  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret