image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/rest-poller-v2
  pullPolicy: IfNotPresent
  tag: "0.2.0" 

env:
  RABBITMQ_CLIENTNAME: dc-smarttaxi-merano
  PROVIDER: smarttaxi/merano

  CRON: "0 */1 * * * *"
  HTTP_URL: https://appclient.smarttaxi.it/terzeparti/elencotassisti/ThrPartMrn2024/91/

envSecretRef:
  - name: RABBITMQ_URI
    secret: rabbitmq-svcbind
    key: uri
