image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-echarging-ocpi
  pullPolicy: IfNotPresent
  tag: 

service:
  enabled: true
  type: ClusterIP
  port: 8080
  health:
    delay: 10
    path: /health

ingress:
  enabled: true

  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

  className: nginx
  tls:
    - hosts:
      - ocpi-neogy.ex.dev.testingmachine.eu
      secretName: tls-ocpi-neogy
  hosts:
    - host: ocpi-neogy.ex.dev.testingmachine.eu
      paths: 
        - path: "/"
          pathType: Prefix
            
env:
  PORT: 8080
  GIN_MODE: release
  LOGLEVEL: DEBUG
  RABBITMQ_EXCHANGE: ingress
  PROVIDER: echarging-ocpi/neogy

envSecret:
  # List of valid tokens, no spaces etc.
  OCPI_TOKENS: ExampleToken1,ExampleToken2

envSecretRef:
  - name: RABBITMQ_URI 
    secret: rabbitmq-svcbind
    key: uri
