# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

nameOverride: dc-echarging-driwe
fullnameOverride: dc-echarging-driwe
image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

imagePullSecrets:
  - name: container-registry-r

resources:
  requests:
    cpu: 1m
    memory: 200Mi

env:
  CRON_SCHEDULE: 0 */2 * * * ?
  INGRESS_PROVIDER: echarging/driwe
  INGRESS_RABBITMQ_CLIENTNAME: echarging-datacollector-driwe
  HTTP_METHOD: GET
  HTTP_HEADERS_X-Caller-ID: NOI-Techpark
envSecret:
  HTTP_ENDPOINT: https://www.driwe.club/api/stations/metadata?auth-token=******
envSecretRef:
  - name: INGRESS_RABBITMQ_URI 
    secret: rabbitmq-svcbind
    key: uri
