nameOverride: dc-rest-poller-echarging-alperia
fullnameOverride: dc-rest-poller-echarging-alperia
image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

imagePullSecrets:
  - name: container-registry-r

resources:
  requests:
    cpu: 1m
    memory: 200Mi 

env:
  CRON_SCHEDULE: 0 */2 * * * ?
  INGRESS_PROVIDER: echarging/alperia
  INGRESS_RABBITMQ_CLIENTNAME: echarging-datacollector-alperia
  HTTP_ENDPOINT: http://api.alperia-emobility.eu/e-mobility/api/v3/chargingunits?includePartners=false
  HTTP_METHOD: GET
  HTTP_HEADERS_X-Caller-ID: NOI-Techpark
envSecretRef:
  - name: INGRESS_RABBITMQ_URI 
    secret: rabbitmq-svcbind
    key: uri
