image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0" 

env:
  RABBITMQ_CLIENTNAME: dc-roomsensor-noi
  PROVIDER: airquality/noi

  CRON: "0 */10 * * * *"

envSecret:
  HTTP_URL: http://saocompute.eurac.edu/sensordb/query?db={{your-dm-name}}&u={{your-username}}&p={{your-passqord}}&q=select%20*%20from%20device_frmpayload_data_message%20order%20by%20time%20limit%2030

envSecretRef:
  - name: RABBITMQ_URI
    secret: rabbitmq-svcbind
    key: uri
