image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0" 
imagePullSecrets:
  - name: container-registry-r

resources:
  requests:
    cpu: 1m
    memory: 200Mi

env:
  CRON_SCHEDULE: 0 */1 * * * ? 
  INGRESS_PROVIDER: smarttaxi/merano
  INGRESS_RABBITMQ_CLIENTNAME: smarttaxi-datacollector-merano
  HTTP_ENDPOINT: https://appclient.smarttaxi.it/terzeparti/elencotassisti/ThrPartMrn2024/91/
  HTTP_METHOD: GET

envSecretRef:
  - name: INGRESS_RABBITMQ_URI
    secret: rabbitmq-svcbind
    key: uri
