services:
  app:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: . 
      target: dev
    env_file:
      - .env
    volumes:
      - ./src:/code
      - pkg:/go/pkg/mod
    working_dir: /code
    # host mode so we can use the port forwards
    network_mode: host 
volumes:
  pkg: