image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-traffic-event-prov-bz
  pullPolicy: IfNotPresent

env:  
  LOG_LEVEL: INFO

  # content writer
  ODH_CORE_URL: https://api.tourism.testingmachine.eu/v1
  ODH_CORE_TOKEN_URL: https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token
  ODH_CORE_TOKEN_CLIENT_ID: 

  MQ_QUEUE: tmp-traffic-event.prov-bz
  MQ_EXCHANGE: routed
  MQ_KEY: tmp-traffic-event.prov-bz
  MQ_CLIENT: tr-traffic-event-prov-bz
  
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_URI
    secret: mongodb-collector-svcbind
    key: uri