replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-parking-offstreet-sfhera
  pullPolicy: IfNotPresent
  tag: sometaghere

imagePullSecrets:
  - name: container-registry-r

env:
  # ODH Core Writer Connection
  BDP_BASE_URL: https://share.opendatahub.testingmachine.eu
  BDP_PROVENANCE_NAME: 
  BDP_PROVENANCE_VERSION: 
  BDP_ORIGIN: Municipality Merano

  LOG_LEVEL: INFO

  # RabbitMQ Connection
  MQ_LISTEN_QUEUE: smarttaxi.merano  
  MQ_LISTEN_EXCHANGE: routed  
  MQ_LISTEN_KEY: smarttaxi.merano 
  MQ_LISTEN_CONSUMER: smarttaxi-datacollector-merano-consumer  

envSecretRef:
  - name: MQ_LISTEN_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_URI
    secret: mongodb-collector-svcbind
    key: uri
  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret
