version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:8080/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - ${SERVER_PORT}:8080
