image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/api-crawler
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

env:
  MQ_CLIENT: dc-api-crawler-carsharing-alpsgo
  PROVIDER: api-crawler/carsharing-alpsgo

  CRON: "0 */5 * * * *"
  HTTP_CONFIG_PATH: "/config/http-config.yaml"
  AUTH_STRATEGY: bearer

  SERVICE_NAME: dc-api-crawler-carsharing-alpsgo
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri

configMap:
  mountPath: "/config/"
  files: {}