image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-api-crawler
  pullPolicy: IfNotPresent
  tag: ""

env:
  LOG_LEVEL: "INFO"
  MQ_CLIENT: dc-api-crawler-parking-swarco
  PROVIDER: api-crawler/parking-swarco

  CRON: "0 0/5 * * * *"
  CONFIG_PATH: "/config/config.yaml"

  SERVICE_NAME: dc-api-crawler-parking-swarco
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri

configMap:
  mountPath: "/config/"
  files: {}
