# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-parking-valgardena
  pullPolicy: IfNotPresent
  tag: sometaghere

imagePullSecrets:
  - name: container-registry-r

env:
  # ODH Core Writer Connection
  LOG_LEVEL: "INFO"

  MQ_QUEUE: parking-valgardena.data
  MQ_EXCHANGE: routed
  MQ_KEY: parking-valgardena.data
  MQ_CLIENT: tr-parking-valgardena-data

  MQ_META_QUEUE: parking-valgardena.metadata
  MQ_META_EXCHANGE: routed
  MQ_META_KEY: parking-valgardena.metadata
  MQ_META_CLIENT: tr-parking-valgardena-metadata

  BDP_BASE_URL: http://bdp-core.core.svc.cluster.local
  BDP_PROVENANCE_VERSION:
  BDP_PROVENANCE_NAME:
  BDP_ORIGIN: GARDENA

  RAW_DATA_BRIDGE_ENDPOINT: http://raw-data-bridge.core.svc.cluster.local:2000

  SERVICE_NAME: tr-parking-valgardena
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri
  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret
