replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-echarging-ocpi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: sometaghere

env:
  # ODH Core Writer Connection
  BDP_BASE_URL: https://share.opendatahub.testingmachine.eu
  BDP_PROVENANCE_NAME: 
  BDP_PROVENANCE_VERSION: 
  BDP_ORIGIN: DRIWE-OCPI
  
  NINJA_URL: https://mobility.api.opendatahub.testingmachine.eu
  
  LOG_LEVEL: INFO

  MQ_EXCHANGE: routed
  MQ_PUSH_QUEUE: echarging-ocpi.driwe
  MQ_PUSH_KEY: echarging-ocpi.driwe
  MQ_POLL_QUEUE: echarging.driwe-ocpi
  MQ_POLL_KEY: echarging.driwe-ocpi

envFrom:
  MQ_CONSUMER: 
    fieldRef:
      fieldPath: metadata.name
    
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_URI
    secret: mongodb-collector-svcbind
    key: uri

  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret