replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-echarging-ocpi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: sometaghere

env:
  # ODH Core Writer Connection
  BDP_BASE_URL: http://bdp-core.core.svc.cluster.local:8080/json
  BDP_PROVENANCE_NAME: 
  BDP_PROVENANCE_VERSION: 
  BDP_ORIGIN: Neogy
  
  LOG_LEVEL: INFO

  MQ_LISTEN_QUEUE: echarging.neogy-ocpi
  MQ_LISTEN_EXCHANGE: routed
  MQ_LISTEN_KEY: echarging.neogy-ocpi
  MQ_LISTEN_CONSUMER: tr-echarging-ocpi-neogy
  
envSecretRef:
  - name: MQ_LISTEN_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_URI
    secret: mongodb-collector-svcbind
    key: uri

  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret