<!--
SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>

SPDX-License-Identifier: CC0-1.0
-->

# @host=http://localhost:{{$dotenv SERVER_PORT}}
@host=https://neogy.ocpi.io.opendatahub.com

### EVSE status update
PATCH {{host}}/ocpi/emsp/2.2/locations/IT/ABC/LOC1/EVSE1
Authorization: Token {{ $dotenv OCPI_TOKENS }}

{
	"status": "CHARGING",
	"last_updated": "2019-06-24T12:39:09Z"
}

### Should get a 400 due to invalid body
PATCH {{host}}/ocpi/emsp/2.2/locations/IT/ABC/LOC1/EVSE1
Authorization: Token TestToken1

### Should get a 401
PATCH {{host}}/ocpi/emsp/2.2/locations/IT/ABC/LOC1/EVSE1
Authorization: Token InvalidToken

### 
GET {{host}}/health