replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-rest-push
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: e8ee3894abe54bd95a712915dcfbf1ac53fd5d14

imagePullSecrets:
  - name: container-registry-r

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true

  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

  className: nginx
  tls:
    - hosts:
      - push.api.dev.testingmachine.eu
      secretName: tls-rest-push
  hosts:
    - host: push.api.dev.testingmachine.eu
      paths: 
        - path: "/"
          pathType: Prefix
            
            
env:
  APP_LOGLEVEL: "INFO"

  APP_SWAGGERURL: "https://swagger.opendatahub.testingmachine.eu/?url=https://push.api.dev.testingmachine.eu/apispec"

  APP_AUTHURL: "https://auth.opendatahub.testingmachine.eu/auth/"
  APP_AUTHREALM: "noi"
  APP_AUTHCLIENTID: "opendatahub-push"

  APP_RABBITCLIENTNAME: "dc-rest-push"

envSecretRef:
  - name: APP_RABBITURL 
    secret: rabbitmq-svcbind
    key: uri