# Default values for generic-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io
  pullPolicy: ifNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
  paths: 
    - path: "/*"
      pathType: ImplementationSpecific
  tls: []

   
service:
  enabled: false
  type: ""
  port: 80
  health:
    delay: 20
    path: /health
  
# A map of key:value environment variables
env:
# A map of sensitive environment variables, they are created as a secret
envSecret:
# A list of (name | secret | key ) tuples that map env variable "name = secret.key"
envSecretRef:
# A map of env entries, where value is a k8s ref type structure, e.g. fieldRef, resourceFieldRef
envFrom:

# ConfigMap definition and mounts: by default, no ConfigMaps are mounted.
configMap:
  files: {}
  mountPath: ""
  subPath: ""
  
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
