image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/google-spreadsheet
  pullPolicy: Always
  tag: "0.0.0" # Set this when upgrading chart with --set-value

imagePullSecrets:
  - name: container-registry-r
    
service:
  enabled: true
  type: ClusterIP
  port: 8082
  health:
    delay: 30
    path: /actuator/health

ingress:
  enabled: true

  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"

  className: nginx
  tls:
    - hosts:
      - spreadsheets.dev.testingmachine.eu
      secretName: tls-spreadsheets
  hosts:
    - host: spreadsheets.dev.testingmachine.eu
      paths: 
        - path: "/traffic-bluetooth/(.*)"
          pathType: Prefix

resources:
  requests:
    cpu: 10m
    memory: 200Mi
    
env:
  SHEETS_APPLICATION_NAME: dc-spreadsheets-google-traffic-bluetooth

  TRIGGER_PATH: trigger
  TRIGGER_PORT: 8082

  INGRESS_PROVIDER: spreadsheets/traffic-bluetooth

  # consolidate update triggers and only update every n milliseconds
  TRIGGER_MAX_UPDATE_FREQUENCY: 20000
  SPREADSHEET_NOTIFICATION_URL: "https://spreadsheets.dev.testingmachine.eu/traffic-bluetooth/trigger"

  GOOGLE_WATCH_EXPIRATION_HOURS: 24
  INGRESS_RABBITMQ_CLIENTNAME: spreadsheet-datacollector-traffic-bluetooth

envSecretRef:
  - name: INGRESS_RABBITMQ_URI 
    secret: rabbitmq-svcbind
    key: uri

envSecret:
  SHEETS_CLIENT_ID: 
  SHEETS_CLIENT_SECRET: 
  SHEETS_REFRESH_TOKEN: 

  SPREADSHEET_ID: 
