# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>harging-alperia
#
# SPDX-License-Identifier: CC0-1.0

nameOverride: tr-meteorology-eurac
fullnameOverride: tr-meteorology-eurac
image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-meteorology-eurac
  pullPolicy: Always
  tag: "0.1.0"

imagePullSecrets:
  - name: container-registry-r
    
env:
  app_dataOrigin: EURAC
  app_period: 600
  
  # ODH Core Writer Connection
  BASE_URI: http://bdp-core.core.svc.cluster.local:8080/json
  scope: openid
  
  # Get it from your pom.xml -> project/version and project/artifactId
  provenance_name: dc-meteorology-eurac-local
  provenance_version: 0.0.0
  
  # Logging level and style (text or json)
  LOG_LEVEL: debug
  LOG_STYLE: json
  
  MQ_LISTEN_KEY: meteorology.eurac
  MQ_LISTEN_QUEUE: meteorology.eurac
  MQ_LISTEN_ACKTIMEOUT: 300000
  
envSecretRef:
  - name: MQ_LISTEN_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_CONNECTIONSTRING
    secret: mongodb-collector-svcbind
    key: uri

  - name: authorizationUri
    secret: oauth-collector
    key: authorizationUri
  - name: tokenUri
    secret: oauth-collector
    key: tokenUri
  - name: clientId
    secret: oauth-collector
    key: clientId
  - name: clientName
    secret: oauth-collector
    key: clientId
  - name: clientSecret
    secret: oauth-collector
    key: clientSecret