# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

@host = http://localhost:8082/trigger
@host=https://google.spreadsheets.io.opendatahub.com
@path=/centro-trevi
@trigger = {{host}}{{path}}/trigger
# The token is generated on application start, you can find it in the log
@token = 2e80718d-e053-4ac6-b947-719148b04557

POST {{trigger}}
X-Goog-Channel-Token: {{token}}