# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

@host = http://localhost:8082/trigger
@host=https://spreadsheets.opendatahub.com
@path=/centro-trevi
@trigger = {{host}}{{path}}/trigger
# The token is generated on application start, you can find it in the log
@token = 2c2cb34d-477e-4582-aa1d-0f4d849d1447

POST {{trigger}}
X-Goog-Channel-Token: {{token}}