apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-collector.fullname" . }}
  labels:
    {{- include "generic-collector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "generic-collector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
            {{- end }}
            {{- range $k, $v := .Values.envSecret }}
            - name: {{ $k | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "generic-collector.envSecretName" $ }}
                  key: {{ $k | quote }}
            {{- end }}
            {{- range $secret := .Values.envSecretRef }}
            - name: {{ $secret.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.secret | quote }}
                  key: {{ $secret.key | quote }}
            {{- end }}
            {{- range $k, $v := .Values.envFrom }}
            - name: {{ $k | quote }}
              valueFrom:
                {{- toYaml $v | nindent 16 }}
            {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.service.health.path }}
              port: http
            initialDelaySeconds: {{ .Values.service.health.delay }}
          readinessProbe:
            httpGet:
              path: {{ .Values.service.health.path }}
              port: http
            initialDelaySeconds: {{ .Values.service.health.delay }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.configMap.files }}
          volumeMounts:
            - name: {{ include "generic-collector.configMapName" $ }}
              mountPath: {{ .Values.configMap.mountPath }}
              {{- if .Values.configMap.subPath }}
              subPath: {{ .Values.configMap.subPath }}
              {{- end }}
          {{- end }}
      {{- if .Values.configMap.files }}
      volumes:
        - name: {{ include "generic-collector.configMapName" $ }}
          configMap:
            name: {{ include "generic-collector.configMapName" $ }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
