image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-mqtt-client
  pullPolicy: IfNotPresent
  tag: "latest" # Set this when upgrading chart with --set-value

env:
  LOG_LEVEL: INFO
  MQTT_CLIENTID: NOI-testing
  MQTT_TOPIC: 
  MQTT_URI: xsona-broker.axians.it:8883
  MQ_CLIENT: dc-mqtt-client-env-a22
  MQ_EXCHANGE: ingress
  PROVIDER: parking-onstreet/bz-axians
envSecret:
  MQTT_PASS:
  MQTT_USER:
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
