image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-mqtt-client
  pullPolicy: IfNotPresent
  tag: "latest" # Set this when upgrading chart with --set-value

env:
  LOG_LEVEL: INFO
  MQTT_CLIENTID: OpenDataHub
  MQTT_TOPIC: people_flow/1dd13058-f04c-f011-8f7d-000d3a3a9b4a
  MQ_CLIENT: dc-mqtt-client-people-me
  MQ_EXCHANGE: ingress
  PROVIDER: people-flow/systems-me
envSecret:
  MQTT_URI:
  MQTT_USER:
  MQTT_PASS:
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
