# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-carsharing-alpsgo
  pullPolicy: IfNotPresent
  tag: sometaghere

imagePullSecrets:
  - name: container-registry-r

env:
  # ODH Core Writer Connection
  LOG_LEVEL: "INFO"
  MQ_QUEUE: multi-rest-poller.carsharing-alpsgo
  MQ_EXCHANGE: routed  
  MQ_KEY: multi-rest-poller.carsharing-alpsgo
  MQ_CLIENT: tr-carsharing-alpsgo

  BDP_BASE_URL: https://mobility.share.opendatahub.com
  BDP_PROVENANCE_VERSION: 
  BDP_PROVENANCE_NAME: 
  BDP_ORIGIN: AlpsGo

  RAW_DATA_BRIDGE_ENDPOINT: http://raw-data-bridge.core.svc.cluster.local:2000

  SERVICE_NAME: tr-carsharing-alpsgo
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret
