replicaCount: 1

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-lorawan
  pullPolicy: IfNotPresent
  tag: sometaghere

imagePullSecrets:
  - name: container-registry-r

env:
  # ODH Core Writer Connection
  LOG_LEVEL: "DEBUG"
  MQ_QUEUE: discoverswiss.lodging  
  MQ_EXCHANGE: routed  
  MQ_KEY: discoverswiss.lodging 
  MQ_CLIENT: discoverswiss-lodging-consumer 
  RAW_FILTER_URL_TEMPLATE: "https://api.tourism.testingmachine.eu/v1/Accommodation?rawfilter=eq(Mapping.discoverswiss.id,%%22%s%%22)&fields=Id"
  ODH_CORE_TOKEN_URL: "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token"
  ODH_CORE_TOKEN_CLIENT_ID: "odh-api-core-discoverswiss"
  ODH_API_CORE_URL: "https://api.tourism.testingmachine.eu/v1/Accommodation"


envSecret:
  ODH_CORE_TOKEN_CLIENT_SECRET: ""

envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_URI
    secret: mongodb-collector-svcbind
    key: uri

