# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

http_calls:
  data_selector_type: json
  nested_calls:
    - url: https://sta.api.weelo.it/resources/locations?languageID=it
      method: GET
      headers:
        Accept: application/json
      data_selector_type: json
      nested_calls:
        - url: https://sta.api.weelo.it/resources/station?languageID=it&stationID=%s
          method: GET
          headers:
            Accept: application/json
          param_selector_type: json
          param_selectors:
            - "$.stations[*].stationID"

          data_destination_field: Station
          data_selector_type: json

    # - url: "${ENDPOINT_URI}/resources/locations"
    #   method: GET
    #   headers:
    #     Accept: application/json
    #   query_params:
    #     languageID: "de"  # German translation
    #   data_selector_type: json
    #   data_selector: $.locations
    #   data_destination_field: locations_translations_de
    #   pagination: null

    # - url: "${ENDPOINT_URI}/resources/locations"
    #   method: GET
    #   headers:
    #     Accept: application/json
    #   query_params:
    #     languageID: "lld"  # Ladin translation
    #   data_selector_type: json
    #   data_selector: $.locations
    #   data_destination_field: locations_translations_lld
    #   pagination: null

    # - url: "${ENDPOINT_URI}/resources/locations"
    #   method: GET
    #   headers:
    #     Accept: application/json
    #   query_params:
    #     languageID: "it"  # Default translation
    #     stationID: "$.stations[*].stationID"
    #   iterate_params: true
    #   data_selector_type: json
    #   data_selector: $.locations
    #   data_destination_field: stations
    #   pagination: null

    # - url: "${ENDPOINT_URI}/resources/station"
    #   method: GET
    #   headers:
    #     Accept: application/json
    #   query_params:
    #     languageID: "en"  # English translation
    #     stationID: "$.stationID"
    #   param_selector_type: json
    #   param_selectors:
    #     - '$.stationID'
    #   data_selector_type: json
    #   data_selector: $.stations
    #   data_destination_field: station_translation_en
    #   pagination: null

    # - url: "${ENDPOINT_URI}/resources/station"
    #   method: GET
    #   headers:
    #     Accept: application/json
    #   query_params:
    #     languageID: "de"  # German translation
    #     stationID: "$.stationID"
    #   param_selector_type: json
    #   param_selectors:
    #     - '$.stationID'
    #   data_selector_type: json
    #   data_selector: $.stations
    #   data_destination_field: station_translation_de
    #   pagination: null

    # - url: "${ENDPOINT_URI}/resources/station"
    #   method: GET
    #   headers:
    #     Accept: application/json
    #   query_params:
    #     languageID: "lld"  # Ladin translation
    #     stationID: "$.stationID"  # station id from parent data
    #   param_selector_type: json
    #   param_selectors:
    #     - '$.stationID'
    #   data_selector_type: json
    #   data_selector: $.stations
    #   data_destination_field: station_translation_lld
    #   pagination: null
# http_calls:
#   data_selector_type: json
#   nested_calls:
#     - url: https://portal.moqo.de/api_aggregator/stations
#       method: GET
#       headers:
#         Accept: application/json
#       data_selector_type: json
#       data_selector: $.stations
#       data_destination_field: stations
#       pagination:
#         request_strategy: query
#         lookup_strategy: increment
#         request_key: page
#         offset_builder:
#           current_start: 1
#           increment: 1
#     - url: https://portal.moqo.de/api_aggregator/vehicles
#       method: GET
#       headers:
#         Accept: application/json
#       data_destination_field: vehicles
#       data_selector: $.vehicles
#       data_selector_type: json
#       pagination:
#         request_strategy: query
#         lookup_strategy: increment
#         request_key: page
#         offset_builder:
#           current_start: 1
#           increment: 1
#     - url: https://portal.moqo.de/api_aggregator/availabilities
#       method: GET
#       headers:
#         Accept: application/json
#       data_destination_field: availabilities
#       data_selector: $.availabilities
#       data_selector_type: json
#       pagination:
#         request_strategy: query
#         lookup_strategy: increment
#         request_key: page
#         offset_builder:
#           current_start: 1
#           increment: 1
