# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

http_call:
  url: https://data.opentransportdata.swiss/dataset/bike-and-car-parking/resource_permalink/bike-and-car-parking.json
  method: GET
  headers:
    Accept: application/json
  data_selector_type: json
