image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-sudtirolwein
  pullPolicy: IfNotPresent

env:
  LOG_LEVEL: INFO

  SOURCE: sudtirolwein
  
  # content writer
  ODH_CORE_URL: https://api.tourism.testingmachine.eu/v1
  ODH_CORE_TOKEN_URL: https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token

  MQ_QUEUE: sudtirolwein
  MQ_EXCHANGE: routed
  MQ_KEY: suedtirolwein.companies
  MQ_CLIENT: dc-sudtirolwein

  RAW_DATA_BRIDGE_ENDPOINT: "http://raw-data-bridge.core.svc.cluster.local:2000"

  SERVICE_NAME: dc-sudtirolwein
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecret:
  ODH_CORE_TOKEN_CLIENT_ID: ""
  ODH_CORE_TOKEN_CLIENT_SECRET: ""

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri
