image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/multi-rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

env:
  MQ_CLIENT: dc-multi-rest-poller-discoverswiss-lodging
  PROVIDER: multi-rest-poller/discoverswiss-lodging

  CRON: "0 0 */2 * * *"
  HTTP_CONFIG_PATH: "/config/http-config.yaml"

  SERVICE_NAME: dc-multi-rest-poller-discoverswiss-lodging
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317
  MQ_URI: amqp://opendatahub:aW9L1RQlVzxuVzxF@rabbitmq-headless.core.svc.cluster.local:5672

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri

configMap:
  mountPath: "/config/"
  files: {}