image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/multi-rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

env:
  MQ_CLIENT: dc-multi-rest-poller-mybestparking
  PROVIDER: multi-rest-poller/mybestparking

  CRON: "0 */1 * * * *"
  HTTP_CALL_CONFIG: "infrastructure/calls_config/mybestparking.yaml"
  AUTH_STRATEGY: oauth2
  OAUTH_METHOD: password
  OAUTH_TOKEN_URL: https://www.mybestinparking.it/oauth/token

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri
