# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-momentus-events
  pullPolicy: IfNotPresent
  tag: latest

env:
  LOG_LEVEL: "INFO"
  MQ_QUEUE: events.momentus
  MQ_EXCHANGE: routed
  MQ_KEY: events.momentus
  MQ_CLIENT: tr-momentus-events-prod
  PROVIDER: events/momentus

  RAW_DATA_BRIDGE_ENDPOINT: http://raw-data-bridge.core.svc.cluster.local:2000

  ODH_VENUE_API: https://tourism.api.opendatahub.com/v1
  VENUE_MAPPING: "{\"NOI TECHPARK\":\"urn:venue:noi:6b3f0a14-3c5b-5d09-81f3-3ebe5b7885ea\",\"EURAC RESEARCH HQ\":\"urn:venue:eurac:df155f71-5cea-5a29-9ebc-213fad6ac1eb\"}"

  ODH_CORE_URL: https://tourism.api.opendatahub.com/v1/
  ODH_CORE_TOKEN_URL: https://auth.opendatahub.com/auth/realms/noi/protocol/openid-connect/token
  ODH_CORE_TOKEN_CLIENT_ID: odh-api-core-events-momentus-serviceaccount

  INSECURE_SKIP_VERIFY: "false"
  SKIP_SSL_VERIFY: "false"

  SERVICE_NAME: tr-momentus-events
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri

envSecret:
  ODH_CORE_TOKEN_CLIENT_SECRET: ""
