# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

image:
  repository: ghcr.io/noi-techpark/odh-collectors/tr-momentus-events

ingress:
  enabled: false

rabbitmq:
  connection: 
    secretName: "opendatahub-amqp-auth-test"

env:
  LOG_LEVEL: "INFO"
  MQ_QUEUE: events.momentus
  MQ_EXCHANGE: routed
  MQ_KEY: events.momentus
  MQ_CLIENT: tr-momentus-events
  ODH_VENUE_API: "https://tourism.api.opendatahub.testingmachine.eu/v1"
  ODH_VENUE_NOI_ID: "urn:venue:noi:6b3f0a14-3c5b-5d09-81f3-3ebe5b7885ea"
  ODH_VENUE_EURAC_ID: "urn:venue:eurac:df155f71-5cea-5a29-9ebc-213fad6ac1eb"

secretEnv:
  - name: MOMENTUS_CLIENT_ID
    secretName: "tr-momentus-auth"
    secretKey: "client_id"
  - name: MOMENTUS_CLIENT_SECRET
    secretName: "tr-momentus-auth"
    secretKey: "client_secret"
