services:
  app:
    depends_on: 
      rabbitmq:
        condition: service_healthy
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: . 
      target: dev
    env_file:
      - .env
    volumes:
      - ./src:/code
      - pkg:/go/pkg/mod
    working_dir: /code
    ports:
      - ${SERVER_PORT}:8080

  rabbitmq:
    extends:
      file: ../lib/docker-compose/docker-compose.rabbitmq.yml
      service: rabbitmq
        
  swagger:
    image: swaggerapi/swagger-ui:v5.17.4
    ports:
      - 8081:8080
    environment:
      URL: http://localhost:8080/apispec
    attach: false
volumes:
  pkg: