image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

env:
  MQ_CLIENT: dc-traffic-event-prov-bz
  PROVIDER: traffic-event/prov-bz

  CRON: "0 */10 * * * *"
  HTTP_URL: "https://www.provinz.bz.it/vmz/traffic.json"

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri
