image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-webcam-feratel
  pullPolicy: IfNotPresent

env:
  LOG_LEVEL: INFO

  # content writer
  ODH_CORE_URL: https://api.tourism.testingmachine.eu/v1
  ODH_CORE_TOKEN_URL: https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token

  MQ_QUEUE: api-crawler.feratel-webcams
  MQ_EXCHANGE: routed
  MQ_KEY: api-crawler.feratel-webcams
  MQ_CLIENT: tr-webcam-feratel

  RAW_DATA_BRIDGE_ENDPOINT: "http://raw-data-bridge.core.svc.cluster.local:2000"

  SERVICE_NAME: tr-webcam-feratel
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecret:
  ODH_CORE_TOKEN_CLIENT_ID: ""
  ODH_CORE_TOKEN_CLIENT_SECRET: ""

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri
