image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/emobility-echarging
  pullPolicy: Always
  tag: "0.1.0"

imagePullSecrets:
  - name: container-registry-r
    
resources:
  requests:
    memory: 200Mi

env:
  # Alperia Config
  app_callerId: NOI-Techpark
  app_dataOrigin: ALPERIA
  app_period: 600
  
  # ODH Core Writer Connection
  BASE_URI: http://bdp-core.core.svc.cal:8080/json
  scope: openid
  
  # Get it from your pom.xml -> project/version and project/artifactId
  provenance_name: dc-emobility-echarging-local
  provenance_version: 0.0.0
  
  # Logging level and style (text or json)
  LOG_LEVEL: info
  LOG_STYLE: json
  
  MQ_LISTEN_KEY: echarging.alperia
  MQ_LISTEN_QUEUE: echarging.alperia
  MQ_LISTEN_ACKTIMEOUT: 300000
  
envSecretRef:
  - name: MQ_LISTEN_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: MONGO_CONNECTIONSTRING
    secret: mongodb-collector-svcbind
    key: uri

  - name: authorizationUri
    secret: oauth-collector
    key: authorizationUri
  - name: tokenUri
    secret: oauth-collector
    key: tokenUri
  - name: clientId
    secret: oauth-collector
    key: clientId
  - name: clientName
    secret: oauth-collector
    key: clientId
  - name: clientSecret
    secret: oauth-collector
    key: clientSecret