name: Build

on:
  push:
    branches: [ "main", "feat/*", "webcamsdata" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Build all Go modules
      run: |
        for dir in $(find . -name go.mod -not -path "*/vendor/*" -exec dirname {} \;); do
          echo "Building module in $dir"
          pushd $dir > /dev/null
          go build -v ./...
          popd > /dev/null
        done
