name: CI/CD dc-google-spreadsheet deployment

on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      environment:
        type: string
        required: true
      spreadsheet-id-secret:
        type: string
        required: true

env:
  WORKING_DIRECTORY: collectors/google-spreadsheet
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/dc-google-spreadsheet
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector
  VALUES_YAML: infrastructure/helm/${{ inputs.name }}.yaml
  K8S_NAME: dc-google-spreadsheet-${{ inputs.name }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency: dc-google-spreadsheet-${{inputs.name}}-${{inputs.environment}}
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Write environment-specific Helm values
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cat <<EOF > override.yml
          image:
            repository:  ${{ env.DOCKER_IMAGE }}
            tag:  ${{ env.DOCKER_TAG }}
            pullPolicy: "IfNotPresent"
          ingress:
            tls:
              - hosts:
                - ${{ vars.G_SHEETS_CALLBACK_HOST }}
                secretName: tls-spreadsheets
            hosts:
              - host: ${{ vars.G_SHEETS_CALLBACK_HOST }}
                paths: 
                  - path: "/${{inputs.name}}/(.*)"
                    pathType: Prefix
          env:
            SPREADSHEET_NOTIFICATION_URL: "https://${{ vars.G_SHEETS_CALLBACK_HOST }}/${{inputs.name}}/trigger"
          envSecret:
            SHEETS_CLIENT_ID: ${{ secrets.G_SHEETS_CLIENT_ID }}
            SHEETS_CLIENT_SECRET:  ${{ secrets.G_SHEETS_CLIENT_SECRET }}
            SHEETS_REFRESH_TOKEN:  ${{ secrets.G_SHEETS_REFRESH_TOKEN }}
            SPREADSHEET_ID:  ${{ secrets[inputs.spreadsheet-id-secret] }}
          EOF

          # Merge yaml files https://mikefarah.gitbook.io/yq/operators/multiply-merge
          yq -i '. *= load("override.yml")' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.K8S_NAME }}
          k8s-namespace: ${{ env.KUBERNETES_NAMESPACE }}
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY}}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1
