name: CI/CD dc-parking-offstreet-famas-bolzano

on: 
  push:
    paths:
      - "collectors/parking-offstreet-famas/**"
      - ".github/workflows/dc-parking-offstreet-famas-bolzano.yml"

env:
  WORKING_DIRECTORY: collectors/parking-offstreet-famas
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/dc-parking-offstreet-famas
  DOCKER_TAG: ${{ github.sha }}
  K8S_NAME: dc-parking-offstreet-famas
  K8s_NAMESPACE: collector
  VALUES_YAML: infrastructure/helm/bolzano.yaml

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency: dc-parking-offstreet-famas-bolzano-build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Run tests
      run: docker run --rm  --volume ./src:/code $(docker build -q . -f infrastructure/docker/Dockerfile --target test)
      working-directory: ${{env.WORKING_DIRECTORY}}

    - name: Build and push images
      uses: noi-techpark/github-actions/docker-build-and-push@v2
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
        docker-username: ${{ github.actor }}
        docker-password: ${{ secrets.GITHUB_TOKEN }}

  deploy-parking-offstreet-famas-bolzano-test:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-24.04
    concurrency: dc-parking-offstreet-famas-bolzano-test
    environment: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yq -i '.image.repository = "${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML }}
          yq -i '.image.tag = "${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
          yq -i '.image.pullPolicy = "IfNotPresent"' ${{ env.VALUES_YAML }}
      

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.K8S_NAME }}
          k8s-namespace: ${{ env.K8s_NAMESPACE }}
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY}}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1