name: CI/CD tr-echarging-ocpi

on: 
  push:
    paths:
      - "transformers/echarging-ocpi/infrastructure/**"
      - "transformers/echarging-ocpi/src/**"
      - ".github/workflows/tr-echarging-ocpi.yml"
      

env:
  WORKING_DIRECTORY: transformers/echarging-ocpi
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/tr-echarging-ocpi
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency: tr-echarging-ocpi-build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build and push images
      uses: noi-techpark/github-actions/docker-build-and-push@v2
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
        docker-username: ${{ github.actor }}
        docker-password: ${{ secrets.GITHUB_TOKEN }}
          
  deploy-driwe-test:
    if: github.ref == 'refs/heads/main'
    needs: 
      - build
    runs-on: ubuntu-22.04
    concurrency: tr-echarging-ocpi-deploy-driwe-test
    environment: test
    env:
      PROJECT_NAME: tr-echarging-ocpi-driwe
      VALUES_YAML: infrastructure/helm/values.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yq -i '
            .image.repository="${{ env.DOCKER_IMAGE }}" |
            .image.tag="${{ env.DOCKER_TAG }}" |
            .image.pullPolicy="IfNotPresent" |

            .env.BDP_PROVENANCE_NAME="${{ env.PROJECT_NAME }}" |
            .env.BDP_PROVENANCE_VERSION="${{ github.sha}}" 

            .env.BASE_URI="https://mobility.share.opendatahub.testingmachine.eu/json" 

          ' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.PROJECT_NAME }}
          k8s-namespace: collector
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_ACCESS_KEY_SECRET }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1

  # deploy-prod:
  #   if: github.ref == 'refs/heads/prod'
  #   needs: 
  #     - build
  #   runs-on: ubuntu-22.04
  #   concurrency: tr-echarging-ocpi-deploy-prod
  #   environment: prod
  #   env:
  #     VALUES_YAML: infrastructure/helm/values.yaml
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - name: Customize values.yaml
  #       working-directory: ${{ env.WORKING_DIRECTORY }}
  #       run: |
  #         yq -i '
  #           .image.repository="${{ env.DOCKER_IMAGE }}" |
  #           .image.tag="${{ env.DOCKER_TAG }}" |
  #           .image.pullPolicy="IfNotPresent" |

  #           .env.BDP_PROVENANCE_NAME="${{ env.PROJECT_NAME }}" |
  #           .env.BDP_PROVENANCE_VERSION="${{ github.sha}}" |
  #           .env.BDP_BASE_URL="https://mobility.share.opendatahub.com"

  #         ' ${{ env.VALUES_YAML }}

  #     - name: Deploy on cluster  
  #       uses: noi-techpark/github-actions/helm-deploy@v2
  #       with:
  #         k8s-name: ${{ env.PROJECT_NAME }}
  #         k8s-namespace: collector
  #         chart-path: helm/generic-collector
  #         values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
  #         aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_PROD_ACCESS_KEY_SECRET }}
  #         aws-eks-cluster-name: aws-main-eu-01
  #         aws-region: eu-west-1