name: CI/CD meteorology-eurac-tr

on: 
  push:
    paths:
      - "transformers/meteorology-eurac/**"
      - ".github/workflows/tr-meteorology-eurac.yml"

env:
  PROJECT_NAME: tr-meteorology-eurac
  WORKING_DIRECTORY: transformers/meteorology-eurac
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/tr-meteorology-eurac
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector
  JAVA_VERSION: 17
  VALUES_YAML: infrastructure/helm/values.yaml

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-test-meteorology-eurac-tr
    environment: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build app and dependencies
        uses: noi-techpark/github-actions/maven-build@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          build-command: |
            mvn -f transformers/lib/rabbit-mongo-listener/pom.xml build-helper:remove-project-artifact clean install \
            && mvn -f ${{ env.WORKING_DIRECTORY }}/pom.xml clean package

      - name: Build and push images
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yq -i '
            .image.repository="${{ env.DOCKER_IMAGE }}" |
            .image.tag="${{ env.DOCKER_TAG }}" |
            .image.pullPolicy="IfNotPresent" |

            .env.provenance_name="${{ env.PROJECT_NAME }}" |
            .env.provenance_version="${{ github.sha}}" 

          ' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.PROJECT_NAME }}
          k8s-namespace: collector
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY}}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_ACCESS_KEY_SECRET }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1