name: CI/CD tr-parking-skidata

on:
  push:
    paths:
      - "transformers/parking-skidata/src/**"
      - "transformers/parking-skidata/resources/**"
      - "transformers/parking-skidata/infrastructure/**"
      - ".github/workflows/tr-parking-skidata.yml"

env:
  WORKING_DIRECTORY: transformers/parking-skidata
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/tr-parking-skidata
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector
  K8S_NAME: tr-parking-skidata

jobs:
  test:
    runs-on: ubuntu-24.04
    concurrency: tr-parking-skidata-test-run
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run tests
        run: docker run --rm $(docker build -q . -f infrastructure/docker/Dockerfile --target test)
        working-directory: ${{ env.WORKING_DIRECTORY }}

  build:
    runs-on: ubuntu-24.04
    concurrency: tr-parking-skidata-build
    needs:
      - test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and push images
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}

  deploy-test:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev/skidata'
    needs: build
    runs-on: ubuntu-24.04
    concurrency: tr-parking-skidata-test
    environment: test
    env:
      VALUES_YAML: infrastructure/helm/values.test.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yq -i '.image.repository="${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML }}
          yq -i '.image.tag="${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
          yq -i '.image.pullPolicy="IfNotPresent"' ${{ env.VALUES_YAML }}
          yq -i '.env.BDP_PROVENANCE_NAME="${{ env.K8S_NAME }}"' ${{ env.VALUES_YAML }}      
          yq -i '.env.BDP_PROVENANCE_VERSION="${{github.sha}}"' ${{ env.VALUES_YAML }}      

      - name: Deploy on cluster
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.K8S_NAME }}
          k8s-namespace: ${{ env.KUBERNETES_NAMESPACE }}
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1

  # deploy-prod:
  #   if: github.ref == 'refs/heads/prod'
  #   needs: build
  #   runs-on: ubuntu-24.04
  #   concurrency: tr-parking-skidata-prod
  #   environment: prod
  #   env:
  #     VALUES_YAML: infrastructure/helm/values.prod.yaml
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - name: Customize values.yaml
  #       working-directory: ${{ env.WORKING_DIRECTORY }}
  #       run: |
  #         yq -i '.image.repository="${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML }}
  #         yq -i '.image.tag="${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
  #         yq -i '.image.pullPolicy="IfNotPresent"' ${{ env.VALUES_YAML }}

  #     - name: Deploy on cluster
  #       uses: noi-techpark/github-actions/helm-deploy@v2
  #       with:
  #         k8s-name: ${{ env.K8S_NAME }}
  #         k8s-namespace: ${{ env.KUBERNETES_NAMESPACE }}
  #         chart-path: helm/generic-collector
  #         values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
  #         aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
  #         aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
  #         aws-eks-cluster-name: aws-main-eu-01
  #         aws-region: eu-west-1
