name: CI/CD tr-traffic-event-prov-bz

on: 
  push:
    paths:
      - "transformers/traffic-event-prov-bz/infrastructure/**"
      - "transformers/traffic-event-prov-bz/src/**"
      - ".github/workflows/tr-traffic-event-prov-bz.yml"

env:
  WORKING_DIRECTORY: transformers/traffic-event-prov-bz
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/tr-traffic-event-prov-bz
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector

jobs:
  test:
    runs-on: ubuntu-24.04
    concurrency: tr-traffic-event-prov-bz-build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Run tests
      run: docker run -it --rm $(docker build -q . -f infrastructure/docker/Dockerfile --target test)
      working-directory: ${{ env.WORKING_DIRECTORY }}

  build:
    runs-on: ubuntu-24.04
    concurrency: tr-traffic-event-prov-bz-build
    needs:
      - test
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build and push images
      uses: noi-techpark/github-actions/docker-build-and-push@v2
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
        docker-username: ${{ github.actor }}
        docker-password: ${{ secrets.GITHUB_TOKEN }}
          
  deploy-test:
    if: github.ref == 'refs/heads/main'
    needs: 
      - build
    runs-on: ubuntu-22.04
    concurrency: tr-traffic-event-prov-bz-deploy-test
    environment: test
    env:
      PROJECT_NAME: tr-traffic-event-prov-bz
      VALUES_YAML: infrastructure/helm/neogy.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yq -i '
            .image.repository="${{ env.DOCKER_IMAGE }}" |
            .image.tag="${{ env.DOCKER_TAG }}" |
            .image.pullPolicy="IfNotPresent" |

            .env.BDP_PROVENANCE_NAME="${{ env.PROJECT_NAME }}" |
            .env.BDP_PROVENANCE_VERSION="${{ github.sha}}"
          ' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.PROJECT_NAME }}
          k8s-namespace: collector
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1
